version: '3'

services:
  apache:
    build:
      context: ./php_password_reset
    ports:
      - "8081:80"
    volumes:
      - ./php_password_reset:/var/www/html
    depends_on:
      - db
      
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: login_db
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

  mailserver:
    image: mailhog/mailhog
    ports:
      - "1025:1025"  # Porta para SMTP
      - "8025:8025"  # Porta para Web UI